version: '3.9'

services:
  fastapi:
    build: ./api
    container_name: fastapi_app
    restart: always
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
    volumes:
      - ./api:/app
    environment:
      - DATABASE_URL=mysql+pymysql://seo_user:yourpassword@db/seo_db
      - REDIS_URL=redis://redis:6379

  celery_worker:
    build: ./api
    container_name: celery_worker
    command: celery -A tasks worker --loglevel=info --concurrency=5
    depends_on:
      - redis
      - db
    volumes:
      - ./api:/app
    environment:
      - DATABASE_URL=mysql+pymysql://seo_user:yourpassword@db/seo_db
      - REDIS_URL=redis://redis:6379

  redis:
    image: redis:alpine
    container_name: redis
    restart: always
    ports:
      - "6379:6379"

  db:
    image: mysql:8.0
    container_name: mysql_db
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: seo_db
      MYSQL_USER: seo_user
      MYSQL_PASSWORD: yourpassword
      MYSQL_ROOT_PASSWORD: rootpassword
    volumes:
      - dbdata:/var/lib/mysql

volumes:
  dbdata:
